### PR TITLE
add SBL 23.09

### PR DESCRIPTION
**Pull request by francescopellegrini**
https://nullsignal.games/blog/standard-ban-list-23-09/

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
i think you gotta update formats.edn

**Comment by francescopellegrini** [comment]
> i think you gotta update formats.edn

Not before the 22nd, right?

**Comment by NoahTheDuke** [comment]
We're just not great about following up lol

**Comment by francescopellegrini** [comment]
> We're just not great about following up lol

I'll open another PR in draft tonight ;)

**Pull request closed without merging**
